services:

  postgres:
    image: postgres:15
    container_name: postgres-etl
    restart: unless-stopped

    environment:
      POSTGRES_DB: etl_python
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password

    ports:
      - "5434:5432"

    volumes:
      - postgres_etl_data:/var/lib/postgresql/data

volumes:
  postgres_etl_data: